import data from '../../../message.json'
// import data , then update when change by hot-loader

const url_message="/api/message.json";

const MessageBox = React.createClass({
  /*
  loadMessage: function() {
    $.ajax({
      url: url_message,
      dataType: 'json',
      cache: false,
      beforeSend: function() {
        console.log('beforeSend')
      },
      success: function(data) {
        console.log(data);
        this.setState({
          data: data
        });
      }.bind(this),
      error: function(xhr, status, err) {
        console.log(this.props.url, status, err);
      }.bind(this)
    });
  },
  */
  messageSubmit: function(comment) {
    var comments = this.state.data;
    // Optimistically set an id on the new comment. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    comment.id = Date.now();
    var newComments = comments.concat([comment]);
    this.setState({data: newComments});
    $.ajax({
      url: url_message,
      dataType: 'json',
      type: 'POST',
      data: comment,
      success: function(data) {
        //this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        this.setState({data: comments});
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
  getInitialState: function() {
    return {data: []};
  },
  componentWillMount:function() {
    this.setState({data:data})
    //this.loadMessage();
    //setInterval(this.loadMessage,2000);
  },
  render:function(){
    console.log(this);
    return (
      <div className="message_box">
      {this.props.children}

    </div>);
  }
});

export default MessageBox;

/* 
      <MessageList data={this.state.data}/>
      <MessageForm onMessageSubmit={this.messageSubmit} />
*/

/*
export
default class MessageBox extends React.Component {
  render() {
    //this.loadMessage();

    return (
      <div className="message_box">
      <MessageList url="/api/message.json"/>
    </div>
    );
  }
}
*/